# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         Net-UCP
version:      0.39
version_from: lib/Net/UCP.pm
installdirs:  site
requires:
    Net::UCP::Common:              0.05
    Net::UCP::IntTimeout:          0.05
    Net::UCP::TransactionManager:  0.02

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.30_01
